'use client';
/* eslint-disable @next/next/no-img-element */
import {useEffect,useState} from 'react';
import {emptyHotel,validateHotel,type Hotel} from '@/lib/hotel-data';
import s from './hotels.module.css';
export function HotelPicker({onPick}:{onPick:(h:Hotel)=>void}){
 const [search,setSearch]=useState(''),[page,setPage]=useState(0),[rows,setRows]=useState<Hotel[]>([]),[more,setMore]=useState(false),[error,setError]=useState('');
 useEffect(()=>{const c=new AbortController();const timer=setTimeout(()=>{fetch('/api/admin/hotels?search='+encodeURIComponent(search)+'&page='+page,{signal:c.signal,cache:'no-store'}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);setRows(j.hotels);setMore(j.hasMore);setError('');}).catch(e=>{if(!c.signal.aborted)setError(e.message);});},200);return()=>{clearTimeout(timer);c.abort();};},[search,page]);
 async function pick(id:string){if(!id)return;try{const r=await fetch('/api/admin/hotels?id='+encodeURIComponent(id),{cache:'no-store'}),j=await r.json();if(!r.ok)throw Error(j.error);onPick(j);}catch(e){setError(String(e));}}
 return <div className={s.box}><label>Find a saved hotel<input value={search} placeholder="Hotel or destination" onChange={e=>{setSearch(e.target.value);setPage(0);}}/></label><select aria-label="Saved hotel" value="" onChange={e=>void pick(e.target.value)}><option value="">Choose a hotel</option>{rows.map(h=><option key={h.id} value={h.id}>{h.name} · {h.destination}{h.active?'':' · Inactive'}</option>)}</select><div><button type="button" disabled={!page} onClick={()=>setPage(page-1)}>Previous</button> <button type="button" disabled={!more} onClick={()=>setPage(page+1)}>Next</button></div>{error&&<p role="alert">{error}</p>}</div>;
}
export function HotelForm({initial,onSaved,onUse}:{initial:Hotel;onSaved:(h:Hotel)=>void;onUse?:(h:Hotel)=>void}){
 const [h,setH]=useState(initial),[error,setError]=useState(''),[busy,setBusy]=useState(false);
 async function photos(files:FileList|null){if(!files)return;setBusy(true);try{const result=[...h.photos];for(const f of Array.from(files)){if(result.length>=3)throw Error('Maximum three photos.');if(!['image/jpeg','image/png'].includes(f.type)||f.size>10000000)throw Error('Choose JPG/PNG up to 10 MB.');const bitmap=await createImageBitmap(f);if(bitmap.width*bitmap.height>40000000){bitmap.close();throw Error('Photo dimensions too large.');}const canvas=document.createElement('canvas'),scale=Math.min(1,1200/Math.max(bitmap.width,bitmap.height));canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);const ctx=canvas.getContext('2d');if(!ctx)throw Error('Photo processing unavailable.');ctx.fillStyle='white';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();let value='';for(const quality of [.8,.65,.5,.35]){value=canvas.toDataURL('image/jpeg',quality);if(value.length<350000)break;}if(value.length>=350000)throw Error('Please resize this photo before uploading.');result.push(value);}setH({...h,photos:result});setError('');}catch(e){setError(String(e));}finally{setBusy(false);}}
 async function save(){setBusy(true);try{validateHotel(h);const r=await fetch('/api/admin/hotels',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(h)}),j=await r.json();if(!r.ok)throw Error(j.error);setH(j);onSaved(j);setError('Hotel saved.');}catch(e){setError(String(e));}finally{setBusy(false);}}
 return <div className={s.box}><div className={s.grid}>{(['name','destination','category','roomType','mealPlan','mapsUrl'] as const).map((k,i)=><label key={k}>{['Hotel name','Destination','Category / rating','Room type','Meal plan','Google Maps share link'][i]}<input value={h[k]} onChange={e=>setH({...h,[k]:e.target.value})}/></label>)}</div><label><input type="checkbox" checked={h.active} onChange={e=>setH({...h,active:e.target.checked})}/> Active hotel</label><label>Hotel photos · up to three<input type="file" multiple accept="image/jpeg,image/png" disabled={busy} onChange={e=>void photos(e.target.files)}/></label><div className={s.grid}>{h.photos.map((p,i)=><div key={i}><img src={p} alt={'Hotel photo '+(i+1)}/><button type="button" onClick={()=>setH({...h,photos:h.photos.filter((_,n)=>n!==i)})}>Remove photo</button></div>)}</div>{error&&<p role="status">{error}</p>}<button type="button" disabled={busy} onClick={()=>void save()}>{busy?'Working…':'Save hotel'+(onUse?' & add to option':'')}</button>{onUse&&<button type="button" disabled={busy} onClick={()=>{try{onUse(validateHotel(h));}catch(e){setError(String(e));}}}>Use only in this quotation</button>}</div>;
}
export default function HotelCatalogue(){const [hotel,setHotel]=useState<Hotel>({...emptyHotel}),[key,setKey]=useState(0);return <section><h2>Your hotel collection</h2><p>Reuse hotel details, photographs and Maps links in future quotations. Supplier contact details remain in Vendors & DMCs.</p><HotelPicker onPick={h=>{setHotel(h);setKey(k=>k+1);}}/><button type="button" onClick={()=>{setHotel({...emptyHotel});setKey(k=>k+1);}}>+ New hotel</button><HotelForm key={key} initial={hotel} onSaved={setHotel}/></section>;}
