'use client';
import Link from 'next/link';
import {useEffect,useRef,useState} from 'react';
import {popupDue,type UpcomingPayload,type TripAlert} from '@/lib/crm-upcoming';
import styles from './today.module.css';
const amount=(n:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0}).format(n);
const storageKey='bucketlist-trip-alerts-v1';
function saveDismissal(day:string,snooze:boolean){try{localStorage.setItem(storageKey,JSON.stringify({day:snooze?'':day,until:snooze?Date.now()+3600000:0}));}catch{}}
export default function CrmToday({visible,summary,onLeads,onPayments}:{visible:boolean;summary:{total:number;new:number;due:number;confirmed:number};onLeads:()=>void;onPayments:()=>void}){
 const [data,setData]=useState<UpcomingPayload|null>(null),[error,setError]=useState(''),[loading,setLoading]=useState(true),[search,setSearch]=useState(''),[range,setRange]=useState('7'),[active,setActive]=useState<TripAlert|null>(null),[showAlerts,setShowAlerts]=useState(false);
 const popup=useRef<HTMLDialogElement>(null),detail=useRef<HTMLDialogElement>(null);
 async function refresh(){setLoading(true);try{const r=await fetch('/api/admin/crm/upcoming',{cache:'no-store'});const j=await r.json();if(!r.ok)throw Error(j.error);setData(j);setError('');}catch(e){setError(e instanceof Error?e.message:'Unable to refresh.');}finally{setLoading(false);}}
 useEffect(()=>{const controller=new AbortController();async function fetchTrips(){try{const r=await fetch('/api/admin/crm/upcoming',{cache:'no-store',signal:controller.signal});const j:UpcomingPayload&{error?:string}=await r.json();if(!r.ok)throw Error(j.error||'Unable to load trips.');setData(j);setError('');let saved={day:'',until:0};try{saved=JSON.parse(localStorage.getItem(storageKey)||'null')||saved;}catch{}if(j.trips.some(t=>t.days<=7)&&popupDue(saved.day,Number(saved.until)))setShowAlerts(true);}catch(e){if(!controller.signal.aborted)setError(e instanceof Error?e.message:'Unable to load.');}finally{if(!controller.signal.aborted)setLoading(false);}}void fetchTrips();const interval=setInterval(()=>{if(document.visibilityState==='visible')void fetchTrips();},300000);return()=>{controller.abort();clearInterval(interval);};},[]);
 useEffect(()=>{if(showAlerts)popup.current?.showModal();else popup.current?.close();},[showAlerts]);
 useEffect(()=>{if(active)detail.current?.showModal();else detail.current?.close();},[active]);
 function dismiss(snooze=false){saveDismissal(data?.today||'',snooze);setShowAlerts(false);}
 const upcoming=data?.trips.filter(t=>t.days<=7)||[],shown=data?.trips.filter(t=>t.days<=Number(range)&&t.title.toLowerCase().includes(search.toLowerCase()))||[],urgent=upcoming.filter(t=>t.days<=1),customerTotal=upcoming.reduce((s,t)=>s+t.customerBalance,0);
 const openTrip=(t:TripAlert)=>{dismiss();setActive(t);};
 const date=(t:TripAlert)=>t.days===0?'Today':t.days===1?'Tomorrow':`In ${t.days} days`;
 return <><div hidden={!visible} className={styles.dashboard}>
 <section className={styles.hero}><div><p className={styles.eyebrow}>THE NEXT ADVENTURE STARTS HERE</p><h2>Make today a little more organised.</h2><p>Upcoming departures, traveller balances and partner accounts—ready when you are.</p><div className={styles.actions}><button onClick={()=>setShowAlerts(true)}>Trip alerts {upcoming.length>0&&<b>{upcoming.length}</b>}</button><button onClick={()=>void refresh()} disabled={loading}>{loading?'Refreshing…':'Refresh'}</button></div></div><div className={styles.heroStat}><strong>{data?upcoming.length:'—'}</strong><span>departures in the next 7 days</span><small>{urgent.length} departing today or tomorrow</small></div></section>
 {error&&<div role="alert" className={styles.notice}>{error} {data&&'Showing the last successfully loaded data.'}</div>}{data?.warnings.map(w=><p role="status" className={styles.notice} key={w}>{w}</p>)}
 <div className={styles.metrics}><button onClick={onLeads}><span>Follow-ups due</span><strong>{summary.due}</strong><small>Open lead pipeline ↗</small></button><button onClick={onPayments}><span>Customer balance · next 7 days</span><strong>{data?amount(customerTotal):'—'}</strong><small>Confirmed bookings only ↗</small></button><Link href="/admin/finance"><span>Vendor accounts</span><strong>Payments & dues</strong><small>Review linked contracts ↗</small></Link></div>
 <section className={styles.tripSection}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>DEPARTURE DESK</p><h2>Your upcoming trips</h2></div><div className={styles.filters}><input aria-label="Search upcoming trips" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search a trip…"/><select aria-label="Upcoming period" value={range} onChange={e=>setRange(e.target.value)}><option value="7">Next 7 days</option><option value="30">Next 30 days</option></select></div></div>
 <div className={styles.cards}>{shown.map(t=><button className={styles.tripCard} key={t.kind+t.id} onClick={()=>setActive(t)}><div className={styles.cardTop}><span data-urgent={t.days<=1}>{date(t)}</span><small>{t.kind==='CUSTOM'?'Custom booking':'Scheduled departure'}</small></div><h3>{t.title}</h3><p>{new Date(t.date+'T12:00:00+05:30').toLocaleDateString('en-IN',{day:'numeric',month:'long',year:'numeric',timeZone:'Asia/Kolkata'})}</p><div className={styles.cardFigures}><span>Travellers<strong>{t.travellers}</strong></span><span>Customer balance<strong>{amount(t.customerBalance)}</strong></span></div><div className={styles.vendorLine}>Vendor balance · estimated INR <b>{t.vendorBalance===null?'Not available':amount(t.vendorBalance)}</b></div>{t.review&&<p className={styles.review}>Payment review required</p>}<footer>Open trip workspace <span>↗</span></footer></button>)}</div>{!shown.length&&<div className={styles.empty}>{loading?'Loading upcoming trips…':error?'Trips unavailable. Use Refresh to try again.':'No departures match this period or search.'}</div>}
 <p className={styles.note}>Dates use India time. Draft, cancelled and completed departures are excluded. Vendor balances cover recorded contracts and use planning exchange rates; an unlinked account shows “Not available”.</p></section>
 </div>
 {!visible&&<button className={styles.floatingAlert} onClick={()=>setShowAlerts(true)}>Trip alerts · {upcoming.length}</button>}
 <dialog ref={popup} className={styles.dialog} aria-labelledby="trip-alert-title" onCancel={e=>{e.preventDefault();dismiss();}}><div className={styles.sectionHead}><div><p className={styles.eyebrow}>BEFORE YOU START</p><h2 id="trip-alert-title">Upcoming adventure alerts</h2></div><button aria-label="Dismiss alerts for today" onClick={()=>dismiss()}>×</button></div><p>{upcoming.length} trips depart within the next 7 days.</p>{error&&<p className={styles.notice}>{error}</p>}{upcoming.map(t=><button className={styles.alertRow} key={t.kind+t.id} onClick={()=>openTrip(t)}><div><strong>{t.title}</strong><small>{date(t)} · {t.date} · {t.travellers} travellers</small></div><span>{t.customerBalance>0?'Balance pending':t.review?'Review payment records':'Review arrangements'} ↗</span></button>)}{!upcoming.length&&<p>{loading?'Loading trips…':'No upcoming trip alerts in this window.'}</p>}<div className={styles.actions}><button onClick={()=>dismiss(true)}>Remind me in 1 hour</button><button onClick={()=>dismiss()}>Dismiss for today</button></div><p className={styles.note}>Preferences apply to this browser. Alerts remain available from the Trip alerts button.</p></dialog>
 <dialog ref={detail} className={styles.dialog} aria-labelledby="trip-workspace-title" onCancel={()=>setActive(null)}>{active&&<><div className={styles.sectionHead}><div><p className={styles.eyebrow}>{date(active)} · {active.date}</p><h2 id="trip-workspace-title">{active.title}</h2></div><button aria-label="Close trip workspace" onClick={()=>setActive(null)}>×</button></div><div className={styles.detailStats}><p>Confirmed travellers<strong>{active.travellers}</strong></p><p>Customer balance<strong>{amount(active.customerBalance)}</strong></p><p>Vendor balance · estimate<strong>{active.vendorBalance===null?'Not available':amount(active.vendorBalance)}</strong></p></div>{active.review&&<p className={styles.notice}>Refund or manual-review records need reconciliation.</p>}<h3>Prepare for departure</h3><ul className={styles.checklist}><li>Check customer balances and traveller details.</li><li>Confirm accommodation, transport and vendor arrangements.</li><li>Review pickup time, meeting point and coordinator details.</li><li>Prepare the itinerary and things-to-carry message.</li></ul><p className={styles.note}>This is a preparation guide, not a record of completed confirmations.</p><div className={styles.actions}><button onClick={()=>{setActive(null);onPayments();}}>Bookings & payments</button><Link href="/admin/finance">{active.financeId?'View vendor accounts':'Link vendor account'} ↗</Link></div><p className={styles.note}>Booking search: {active.title} · {active.date}. Automated customer/vendor messages are not enabled in this dashboard release.</p></>}</dialog>
 </>;
}
