'use client';
/* eslint-disable @next/next/no-img-element -- Uploaded inline images preserve their original proportions. */
import {useEffect,useState} from 'react';
import type {QuotationContent,QuoteBooking} from '@/lib/quotation-data';
import {mapsLink} from '@/lib/hotel-data';
import styles from './proposal.module.css';
type Proposal={booking:QuoteBooking;content:QuotationContent;revision:number;expiresAt:string;acceptedAt:string|null;acceptedOptionId:string|null;acceptedName:string|null;payment:{url:string;amount:number;label:string}|null};
const money=(v:number)=>new Intl.NumberFormat('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:2}).format(v);
const date=(v:string)=>v?new Intl.DateTimeFormat('en-IN',{day:'numeric',month:'short',year:'numeric',timeZone:'Asia/Kolkata'}).format(new Date(v.length===10?v+'T00:00:00+05:30':v)):'To be confirmed';
async function readResponse(r:Response){if(!r.headers.get('content-type')?.includes('application/json'))throw Error('The proposal service is unavailable. Please try again shortly.');const value=await r.json();if(!r.ok)throw Error(value.error||'Unable to load proposal.');return value as Proposal;}
export default function ProposalView({token}:{token:string}){
 const [proposal,setProposal]=useState<Proposal|null>(null),[error,setError]=useState(''),[busy,setBusy]=useState(false),[option,setOption]=useState(''),[name,setName]=useState(''),[agreed,setAgreed]=useState(false);
 useEffect(()=>{const controller=new AbortController();fetch('/api/proposals/'+encodeURIComponent(token),{cache:'no-store',signal:controller.signal}).then(readResponse).then(p=>{setProposal(p);setOption(p.acceptedOptionId??p.content.selectedOptionId);}).catch(e=>{if(!controller.signal.aborted)setError(e.message);});return()=>controller.abort();},[token]);
 const whatsapp='https://wa.me/919225531257?text='+encodeURIComponent('Hello Bucketlist Adventure, I would like to discuss '+(proposal?'proposal '+proposal.booking.reference:'my travel proposal')+'.');
 const textSection=(heading:string,value:string)=>value.trim()?<section className={styles.section}><p className={styles.eyebrow}>YOUR JOURNEY</p><h2>{heading}</h2><p className={styles.copy}>{value}</p></section>:null;
 if(!proposal)return <main className={styles.shell}><div className={styles.message}><p className={styles.eyebrow}>BUCKETLIST ADVENTURE</p><h1>{error?'Let’s reconnect you with your journey.':'Your journey is on its way…'}</h1><p role="status">{error||'Loading your personal proposal.'}</p>{error&&<a href={whatsapp} rel="noreferrer" className={styles.primary}>Contact your travel team</a>}</div></main>;
 const {booking:b,content:q}=proposal;
 const selected=q.options.find(o=>o.id===option),price=selected?.total??b.total;
 return <main className={styles.shell}>
  <header className={styles.header}><a href="https://bucketlistadventure.in" rel="noreferrer">BUCKETLIST ADVENTURE<span>We plan it. You live it.</span></a><span>PERSONAL TRAVEL PROPOSAL · {proposal.revision}</span></header>
  <section className={styles.hero}><div><p className={styles.eyebrow}>PREPARED FOR {b.customer}</p><h1>{b.title}</h1><p>{q.intro}</p><div className={styles.chips}><span>{b.travellers} travellers</span><span>{date(b.start)} — {date(b.end)}</span></div><a href="#your-package" className={styles.primary}>Explore your package ↓</a></div>{q.cover&&<img src={q.cover} alt={b.title} className={styles.cover}/>}</section>
  <div className={styles.layout}><div>
   {textSection('The route',q.route)}
   {textSection('Your accommodation',q.hotels)}
   <section className={styles.section} id="your-package"><p className={styles.eyebrow}>MAKE IT YOURS</p><h2>{q.options.length?'Choose your package':'Your package'}</h2><p>Prices are for the whole group. Choose one package; alternative prices are not added together.</p>
    {q.options.length?<fieldset className={styles.options} disabled={busy||!!proposal.acceptedAt}><legend className={styles.srOnly}>Package choices</legend>{q.options.map(o=><label key={o.id} className={`${styles.option} ${option===o.id?styles.selected:''}`}><input type="radio" name="package" value={o.id} checked={option===o.id} onChange={()=>setOption(o.id)}/><span><strong>{o.name}</strong><span>{money(o.total)} for your group</span><small>{o.notes}</small></span></label>)}</fieldset>:<p className={styles.price}>{money(b.total)}</p>}
    {(selected?[selected]:q.options).map(o=><div key={o.id}><h3>{o.name}</h3><p>{[o.rooms?`${o.rooms} rooms`:'',o.extraMattresses?`${o.extraMattresses} extra mattresses`:'',o.extraMeals?`${o.extraMeals} extra meals`:'',o.cabType,o.cabCount?`${o.cabCount} vehicles`:'',o.luggageCabs?`${o.luggageCabs} luggage vehicles`:''].filter(Boolean).join(' · ')}</p>{o.stays.map((h,i)=><article className={styles.hotel} key={h.id+'-'+i}><h3>{h.name}</h3><p>{h.destination} · {h.nights} nights {h.alternative?'· Alternative hotel':''}</p><p>{[h.category,h.roomType,h.mealPlan].filter(Boolean).join(' · ')}</p><div className={styles.photos}>{h.photos.map((src,n)=><img key={n} src={src} alt={`${h.name} photograph ${n+1}`} loading="lazy"/>)}</div>{mapsLink(h.mapsUrl)&&<a href={mapsLink(h.mapsUrl)} target="_blank" rel="noreferrer">View on Google Maps ↗</a>}<small>Subject to availability at confirmation.</small></article>)}</div>)}
   </section>
   <section className={styles.section}><p className={styles.eyebrow}>THE EXPERIENCE</p><h2>Your days, thoughtfully planned.</h2>{q.itinerary.split(/\n(?=\s*day\s*\d)/i).filter(Boolean).map((day,i)=>{const [title,...body]=day.split('\n');return <article className={styles.day} key={i}><span>{String(i+1).padStart(2,'0')}</span><div><h3>{title}</h3><p className={styles.copy}>{body.join('\n')}</p></div></article>;})}</section>
   <div className={styles.inclusions}>{textSection('Included',q.includes)}{textSection('Not included',q.excludes)}</div>
   {textSection('Pricing & taxes',q.pricingNote)}{textSection('Booking & cancellation terms',q.terms)}
  </div><aside className={styles.summary}><p className={styles.eyebrow}>YOUR NEXT ADVENTURE</p><h2>{selected?.name||b.title}</h2><p className={styles.price}>{money(price)}</p><p>For {b.travellers} travellers{b.travellers>0?' · '+money(price/b.travellers)+' average per person':''}</p><p>Valid until {date(q.validUntil)}</p>
   {proposal.acceptedAt?<div role="status"><h3>Thank you, {proposal.acceptedName}.</h3><p>Your acceptance is recorded for revision {proposal.revision}. Your travel team will confirm availability and booking status.</p>{proposal.payment?<a className={styles.primary} href={proposal.payment.url} rel="noreferrer">Pay {money(proposal.payment.amount)} securely ↗</a>:<p>Your travel team will review your selection and arrange any payment due.</p>}</div>:<form onSubmit={async e=>{e.preventDefault();if(busy)return;setBusy(true);setError('');try{const p=await readResponse(await fetch('/api/proposals/'+encodeURIComponent(token),{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({option,name,agreed})}));setProposal(p);setOption(p.acceptedOptionId??option);}catch(e){setError(e instanceof Error?e.message:'Unable to record acceptance.');}finally{setBusy(false);}}}><label>Your full name<input required minLength={2} maxLength={120} value={name} onChange={e=>setName(e.target.value)} disabled={busy} autoComplete="name"/></label><label className={styles.consent}><input type="checkbox" required checked={agreed} onChange={e=>setAgreed(e.target.checked)} disabled={busy}/><span>I have reviewed this proposal, the selected package, pricing and booking terms, and agree to proceed.</span></label><button className={styles.primary} disabled={busy||!agreed||(!!q.options.length&&!selected)}>{busy?'Recording your acceptance…':'Accept this proposal'}</button><small>Acceptance records your choice. Your booking remains subject to availability and payment confirmation.</small></form>}
   {error&&<p role="alert" className={styles.error}>{error}</p>}<a href={whatsapp} rel="noreferrer" className={styles.secondary}>Ask a question / request changes ↗</a><small>Reference: {b.reference}. Keep this private link with your travel group.</small>
  </aside></div><footer className={styles.footer}>Bucketlist Adventure · bookings@bucketlistadventure.in · +91 9225531257</footer>
 </main>;
}
