'use client';
import {useState} from 'react';
import {HotelPicker,HotelForm} from '../finance/HotelCatalogue';
import {emptyHotel,type Hotel,type PackageOption} from '@/lib/hotel-data';
import s from '../finance/hotels.module.css';
export function newOption(total:number,name='Package 1'):PackageOption{return {id:crypto.randomUUID(),name,total,included:true,notes:'',rooms:1,extraMattresses:0,extraMeals:0,cabType:'',cabCount:0,luggageCabs:0,stays:[]};}
export default function PackageOptions({options,selected,total,pax,onChange}:{options:PackageOption[];selected:string;total:number;pax:number;onChange:(o:PackageOption[],s:string)=>void}){
 const [manual,setManual]=useState('');
 function update(i:number,p:PackageOption){onChange(options.map((o,n)=>n===i?p:o),selected);}
 function addHotel(i:number,h:Hotel){if(options[i].stays.length>=12)return;update(i,{...options[i],stays:[...options[i].stays,{...h,photos:[...h.photos],nights:1,alternative:false}]});setManual('');}
 return <article className={s.box}><h2>Package options & hotels</h2><p>Offer up to six alternatives. Each total is for the whole group. Room and vehicle counts describe the offer; they do not calculate supplier costs.</p><div className={s.grid}>{options.map(o=><div className={s.banner} key={o.id}><span>{o.name}{o.included?'':' · Excluded from PDF'}</span><br/><strong>₹{o.total.toLocaleString('en-IN')}</strong><br/>{pax>0?'₹'+(o.total/pax).toLocaleString('en-IN',{maximumFractionDigits:2})+' average per person':''}</div>)}</div>
 <label>Accepted package<select value={selected} onChange={e=>onChange(options,e.target.value)}><option value="">Customer has not selected a package</option>{options.filter(o=>o.included).map(o=><option key={o.id} value={o.id}>{o.name}</option>)}</select></label><small>A payment button is eligible only when the accepted option matches the booking total and its installment link remains valid.</small>
 {options.map((o,i)=><details key={o.id} className={s.box} open><summary>{o.name} · ₹{o.total.toLocaleString('en-IN')}</summary><label><input type="checkbox" checked={o.included} onChange={e=>update(i,{...o,included:e.target.checked})}/> Include in customer PDF</label><div className={s.grid}><label>Package name<input value={o.name} maxLength={120} onChange={e=>update(i,{...o,name:e.target.value})}/></label><label>Final group price (INR)<input type="number" min="0.01" step="0.01" value={o.total||''} onChange={e=>update(i,{...o,total:Number(e.target.value)})}/></label>{(['rooms','extraMattresses','extraMeals','cabCount','luggageCabs'] as const).map((k,n)=><label key={k}>{['Rooms','Extra mattresses','Extra meals','Vehicles','Luggage vehicles'][n]}<input type="number" min="0" max="999" value={o[k]} onChange={e=>update(i,{...o,[k]:Number(e.target.value)})}/></label>)}<label>Vehicle type<input value={o.cabType} onChange={e=>update(i,{...o,cabType:e.target.value})}/></label></div><label>Package differences / notes<textarea value={o.notes} rows={3} onChange={e=>update(i,{...o,notes:e.target.value})}/></label>
 <div className={s.grid}>{[...new Set(o.stays.map(h=>h.destination))].map(dest=><div key={dest}><h3>{dest}</h3>{o.stays.filter(h=>h.destination===dest).map((h,n)=><p key={n}>{h.name} · {h.nights}N {h.alternative?'(alternative)':''}<small>{h.roomType} · {h.mealPlan}</small></p>)}</div>)}</div>
 {o.stays.map((h,n)=><div key={n} className={s.box}><h3>{h.name}</h3><div className={s.grid}>{(['name','destination','roomType','mealPlan','mapsUrl'] as const).map(k=><label key={k}>{({name:'Hotel name',destination:'Destination',roomType:'Room type',mealPlan:'Meal plan',mapsUrl:'Google Maps link'})[k]}<input value={h[k]} onChange={e=>update(i,{...o,stays:o.stays.map((v,m)=>m===n?{...v,[k]:e.target.value}:v)})}/></label>)}<label>Nights<input type="number" min="1" max="365" value={h.nights} onChange={e=>update(i,{...o,stays:o.stays.map((v,m)=>m===n?{...v,nights:Number(e.target.value)}:v)})}/></label></div><label><input type="checkbox" checked={h.alternative} onChange={e=>update(i,{...o,stays:o.stays.map((v,m)=>m===n?{...v,alternative:e.target.checked}:v)})}/> Alternative hotel (not additional nights)</label><small>{h.photos.length} photo(s) included. Hotels are proposed, subject to availability.</small><button type="button" onClick={()=>update(i,{...o,stays:o.stays.filter((_,m)=>m!==n)})}>Remove hotel</button></div>)}
 {o.stays.length<12&&<><HotelPicker onPick={h=>{if(h.active)addHotel(i,h);}}/><button type="button" onClick={()=>setManual(manual===o.id?'':o.id)}>+ Add hotel manually</button>{manual===o.id&&<HotelForm initial={{...emptyHotel}} onSaved={h=>addHotel(i,h)} onUse={h=>addHotel(i,h)}/>}</>}<button type="button" onClick={()=>onChange(options.filter((_,n)=>n!==i),selected===o.id?'':selected)}>Remove package</button></details>)}
 <button type="button" disabled={options.length>=6} onClick={()=>onChange([...options,newOption(total,['Budget','Standard','Premium','Deluxe','Luxury','Elite'][options.length])],selected)}>+ Add package option</button></article>;
}
