'use client';
import {useCallback,useEffect,useState} from 'react';
type Revision={superseded:boolean;expired:boolean;id:string;revision:number;created_at:string;expires_at:string;viewed_at:string|null;revoked_at:string|null;accepted_at:string|null;accepted_name:string|null;accepted_option_id:string|null};
async function json(r:Response){if(!r.headers.get('content-type')?.includes('application/json'))throw Error('Proposal sharing is unavailable. Restart the server or check the deployment.');const j=await r.json();if(!r.ok)throw Error(j.error||'Unable to update proposal sharing.');return j;}
export default function ProposalShare({bookingId,disabled}:{bookingId:string;disabled:boolean}){
 const [rows,setRows]=useState<Revision[]>([]),[link,setLink]=useState(''),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false);
 const endpoint='/api/custom-bookings/'+encodeURIComponent(bookingId)+'/proposal';
 const refresh=useCallback(async()=>{const j=await json(await fetch(endpoint,{cache:'no-store'}));setRows(j.revisions);},[endpoint]);
 useEffect(()=>{let active=true;fetch(endpoint,{cache:'no-store'}).then(json).then(j=>{if(active)setRows(j.revisions);}).catch(e=>{if(active)setNotice(e.message);});return()=>{active=false;};},[endpoint]);
 async function act(method:'POST'|'DELETE'){
  if(busy||disabled)return;setBusy(true);setNotice('');
  try{const j=await json(await fetch(endpoint,{method}));setLink(method==='POST'?new URL(j.path,window.location.origin).href:'');setNotice(method==='POST'?'Private link created. Copy and send it to your customer. Previous links are revoked.':'All existing customer links revoked.');await refresh();}catch(e){setNotice(e instanceof Error?e.message:'Unable to update proposal sharing.');}finally{setBusy(false);}
 }
 return <section style={{marginTop:24,borderTop:'1px solid #ccd3c7',paddingTop:20,display:'grid',gap:12}}><h3>Customer proposal link</h3><p style={{fontSize:13}}>Share an online proposal so your customer can review options and accept. Creating a new link saves a revision and revokes previous links.</p><button type="button" disabled={disabled||busy} onClick={()=>void act('POST')}>{busy?'Working…':'Create new customer link'}</button>{link&&!disabled&&<><label>Private proposal URL<input readOnly value={link} onFocus={e=>e.target.select()} style={{width:'100%'}}/></label><button type="button" onClick={async()=>{try{await navigator.clipboard.writeText(link);setNotice('Link copied. Share it privately with your customer.');}catch{setNotice('Select the URL above and copy it manually.');}}}>Copy customer link</button><a href={link} target="_blank" rel="noreferrer">Preview customer proposal ↗</a></>}<button type="button" disabled={disabled||busy||!rows.some(r=>!r.revoked_at)} onClick={()=>void act('DELETE')}>Revoke customer links</button><button type="button" disabled={busy} onClick={()=>void refresh().catch(e=>setNotice(e.message))}>Refresh acceptance status</button>{notice&&<p role="status" style={{fontSize:13}}>{notice}</p>}
 <small>Saving changes to a shared quotation makes its old link unavailable. Create a new link after saving. Link possession grants access; copy it now, as it cannot be recovered here later. Previewing a link counts as a view, not proof that the customer read it.</small>
 {rows.length>0&&<details><summary>Revision history ({rows.length})</summary>{rows.map(r=><div key={r.id} style={{borderTop:'1px solid #ccd3c7',padding:'12px 0',fontSize:13}}><strong>Revision {r.revision} · {r.revoked_at?'Revoked':r.superseded?'Quotation edited':r.expired?'Expired':r.accepted_at?'Accepted':r.viewed_at?'Viewed':'Link created'}</strong><p>Created {new Date(r.created_at).toLocaleString()}</p>{r.accepted_at&&<p>Accepted by {r.accepted_name} on {new Date(r.accepted_at).toLocaleString()}. Package: {r.accepted_option_id||'Standard package'}. Review the selection against Custom Bookings before arranging payment.</p>}</div>)}</details>}
 </section>;
}
