'use client';
import Link from 'next/link';
import {useEffect,useState,type FormEvent} from 'react';
import {emptyQuotation,type QuotationContent,type QuoteBooking} from '@/lib/quotation-data';
import styles from './quotation.module.css';
export default function QuotationEditor(){
 const [id,setId]=useState(''),[booking,setBooking]=useState<QuoteBooking|null>(null),[content,setContent]=useState({...emptyQuotation}),[message,setMessage]=useState(''),[busy,setBusy]=useState(false),[saved,setSaved]=useState(false),[dirty,setDirty]=useState(false),[payable,setPayable]=useState(false);
 useEffect(()=>{const value=new URLSearchParams(window.location.search).get('booking')||'';const controller=new AbortController();if(!value)return;fetch('/api/custom-bookings/'+encodeURIComponent(value)+'/quotation',{cache:'no-store',signal:controller.signal}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.error);return j;}).then(j=>{setId(value);setBooking(j.booking);setContent(j.content);setSaved(j.saved);setPayable(Boolean(j.payment));}).catch(e=>{if(!controller.signal.aborted)setMessage(e.message);});return()=>controller.abort();},[]);
 function change(k:keyof QuotationContent,value:string){setContent(c=>({...c,[k]:value}));setDirty(true);}
 async function save(e:FormEvent){e.preventDefault();if(busy||!id)return;setBusy(true);setMessage('');try{const r=await fetch('/api/custom-bookings/'+id+'/quotation',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(content)});const j=await r.json();if(!r.ok)throw Error(j.error);setSaved(true);setDirty(false);const rr=await fetch('/api/custom-bookings/'+id+'/quotation',{cache:'no-store'});const jj=await rr.json();if(!rr.ok)throw Error('Saved, but refresh failed. Reload before downloading.');setPayable(Boolean(jj.payment));setMessage('Quotation saved. You can download the PDF.');}catch(e){setMessage(e instanceof Error?e.message:'Unable to save.');}finally{setBusy(false);}}
 async function photo(file:File|undefined){if(!file)return;if(!['image/jpeg','image/png'].includes(file.type)||file.size>1572864){setMessage('Choose a JPG or PNG up to 1.5 MB.');return;}try{const value=await new Promise<string>((resolve,reject)=>{const r=new FileReader();r.onload=()=>resolve(String(r.result));r.onerror=reject;r.readAsDataURL(file);});change('cover',value);}catch{setMessage('Could not read this photo.');}}
 const field=(key:keyof QuotationContent,label:string,hint:string,required=false)=><label>{label}<small>{hint}</small><textarea value={content[key]} required={required} maxLength={key==='itinerary'?30000:10000} rows={key==='itinerary'?14:5} onChange={e=>change(key,e.target.value)}/></label>;
 return <main className={styles.shell}><header><div><p className={styles.eyebrow}>BUCKETLIST / QUOTATION STUDIO</p><h1>A journey, beautifully presented.</h1><p>Prepare a personalised proposal with your booking price and payment schedule.</p></div><Link href="/admin?section=custom-bookings">Back to custom bookings ↗</Link></header>{message&&<p role="status" className={styles.notice}>{message}</p>}{!booking?<p>Open “Prepare quotation” on a custom booking to begin. {message?'Check the error above.':'Loading if a booking was selected…'}</p>:<form onSubmit={save}><div className={styles.layout}><section className={styles.editor}>
 <article><h2>First impressions</h2><label>Quotation valid until<input type="date" required value={content.validUntil} onChange={e=>change('validUntil',e.target.value)}/></label><label>Cover photograph<small>Your own destination photo, JPG or PNG up to 1.5 MB.</small><input type="file" accept="image/jpeg,image/png" onChange={e=>void photo(e.target.files?.[0])}/></label>{content.cover&&<><div className={styles.cover} style={{backgroundImage:`url("${content.cover}")`}} role="img" aria-label="Quotation cover preview"/><button type="button" onClick={()=>change('cover','')}>Remove photo</button></>}{field('intro','Personal introduction','Make the guest feel welcome.')}{field('route','Route & overnight stays','For example: 2N Leh / 2N Nubra / 1N Pangong.')}</article>
 <article><h2>The experience</h2>{field('hotels','Accommodation','Hotel names, room categories, occupancy, nights and meal plans. Label unconfirmed hotels clearly.')}{field('itinerary','Day-by-day itinerary','Use a day heading, followed by its description. Add a new line for each day.',true)}{field('includes','Inclusions','One inclusion per line.',true)}{field('excludes','Exclusions','One exclusion per line.',true)}</article>
 <article><h2>Clear terms, confident booking</h2>{field('pricingNote','Pricing & tax note','State whether the booking total includes taxes. Specify any payable extras. This does not alter the booking price.',true)}{field('terms','Booking & cancellation terms','Enter the terms agreed for this quotation. Do not promise unconfirmed availability.')}</article>
 </section><aside className={styles.summary}><p className={styles.eyebrow}>YOUR PROPOSAL</p><h2>{booking.title}</h2><p>Prepared for <strong>{booking.customer}</strong></p><dl><dt>Booking reference</dt><dd>{booking.reference}</dd><dt>Travel dates</dt><dd>{booking.start||'Not set'} — {booking.end||'Not set'}</dd><dt>Travellers</dt><dd>{booking.travellers}</dd><dt>Total package price</dt><dd>INR {booking.total.toLocaleString('en-IN')}</dd><dt>Paid so far</dt><dd>INR {booking.paid.toLocaleString('en-IN')}</dd></dl><p className={styles.hint}>Price and installments come from the custom booking. Change them there before issuing a revised quotation.</p><button type="submit" disabled={busy}>{busy?'Saving…':'Save quotation'}</button>{saved&&!dirty&&!busy&&<a className={styles.download} href={'/api/custom-bookings/'+id+'/quotation?format=pdf'}>Download quotation PDF ↓</a>}{dirty&&<p className={styles.hint}>Save your changes before downloading.</p>}<p className={styles.hint}>{payable?'An active unpaid installment link is available. The PDF checks it again at download.':'No eligible payment link currently available. Generate or refresh the next unpaid installment link in Custom Bookings, then reload this page after saving.'}</p><p className={styles.hint}>PDF payment buttons are omitted for expired quotes, expired links, cancelled/completed/review bookings or fully paid installments. Creating a PDF does not generate or send payment links.</p></aside></div></form>}</main>;
}
