'use client';
import {useEffect,useState} from 'react';
import type {ReminderJob,ReminderSettings,ReminderTrip} from '@/lib/trip-reminder-plan';
import styles from './reminders.module.css';
type History={id:string;recipient:string;subject:string;status:string;created_at:string};
type Data={sources:ReminderTrip[];jobs:ReminderJob[];history:History[];warnings:string[];enabled:boolean};
export default function ReminderWorkspace(){
 const [data,setData]=useState<Data|null>(null),[setting,setSetting]=useState<ReminderSettings|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/trip-reminders',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Please sign in to admin again.');setData(d);return d as Data;}
 useEffect(()=>{let active=true;fetch('/api/admin/trip-reminders',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Please sign in to admin again.');if(active)setData(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[]);
 async function action(body:object){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/trip-reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.error);setMessage(result.message);await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to complete action.');}finally{setBusy(false);}}
 return <main className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>BUCKETLIST / TRAVELLER CARE</p><h1>Stay connected, every step.</h1><p>Prepare travellers, coordinate with vendors and celebrate journeys completed.</p></div><a href="/admin/crm">Back to CRM ↗</a></header>
 <div className={styles.toolbar}><span>Automatic sending: {data?.enabled?'Enabled — scheduler required':'Off'}</span><button disabled={busy} onClick={()=>void action({action:'test'})}>Send branded test to info@bucketlistadventure.in</button></div>
 {message&&<p role="status" className={styles.notice}>{message}</p>}{data?.warnings.map(w=><p className={styles.notice} key={w}>{w}</p>)}
 <div className={styles.grid}><section className={styles.panel}><h2>Trip reminders</h2><p>Emails at 7, 3 and 1 day before departure. Review requests the day after the trip, for bookings marked Completed.</p><label>Choose a trip<select value={setting?.id||''} onChange={e=>setSetting(data?.sources.find(s=>s.id===e.target.value)?.setting||null)}><option value="">Select a departure or custom booking</option>{data?.sources.map(s=><option key={s.id} value={s.id}>{s.start} · {s.title} · {s.id.startsWith('CUSTOM')?'Custom':'Departure'}</option>)}</select></label>
 {setting&&<><label>Meeting point, time and coordinator contact<textarea value={setting.details} maxLength={6000} onChange={e=>setSetting({...setting,details:e.target.value})}/></label><label>Things to carry<textarea value={setting.checklist} maxLength={6000} onChange={e=>setSetting({...setting,checklist:e.target.value})}/></label><label>Travel tips<textarea value={setting.tips} maxLength={6000} onChange={e=>setSetting({...setting,tips:e.target.value})}/></label>{(['customer_enabled','vendor_enabled','review_enabled'] as const).map((key,i)=><label className={styles.check} key={key}><input type="checkbox" checked={setting[key]} onChange={e=>setSetting({...setting,[key]:e.target.checked})}/>{['Customer preparation emails','Vendor coordination emails','Post-trip thank-you and review email'][i]}</label>)}<button disabled={busy} onClick={()=>void action({action:'save',...setting})}>Save reminder settings</button></>}
 </section><section className={styles.panel}><h2>Message previews & WhatsApp</h2><p>Save settings to see eligible messages for the next 30 days. WhatsApp opens a prepared message for you to review and send.</p>{data?.jobs.filter(j=>!setting||j.id.includes(setting.id)).map(j=><details key={j.id}><summary>{j.date} · {j.kind.replaceAll('_',' ')}<br/>{j.trip}</summary><p>{j.recipient||'No email address — WhatsApp only'}</p><pre>{j.message}</pre>{j.whatsapp&&<a className={styles.link} href={j.whatsapp} target="_blank" rel="noreferrer">Open WhatsApp message ↗</a>}</details>)}{data&&!data.jobs.length&&<p>No eligible messages yet. Select a trip and enable its reminders.</p>}</section></div>
 <section className={styles.panel}><h2>Recent email activity</h2><p>Sent means accepted by the mail server. Uncertain or long-running Processing messages need checking before any manual resend.</p><div className={styles.table}><table><thead><tr><th>Time</th><th>Recipient</th><th>Subject</th><th>Status</th></tr></thead><tbody>{data?.history.map(h=><tr key={h.id}><td>{new Date(h.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td>{h.recipient}</td><td>{h.subject}</td><td>{h.status}</td></tr>)}</tbody></table></div></section></main>;
}
