'use client';
import {useEffect,useState} from 'react';
import type {ManualReminder,ReminderJob,ReminderSettings,ReminderTrip} from '@/lib/trip-reminder-plan';
import styles from './reminders.module.css';
type History={id:string;recipient:string;subject:string;status:string;created_at:string};
type Data={sources:ReminderTrip[];jobs:ReminderJob[];history:History[];warnings:string[];enabled:boolean;manualPreviews?:ManualReminder[];manualReasons?:Record<string,string>};
export default function ReminderWorkspace(){
 const [data,setData]=useState<Data|null>(null),[setting,setSetting]=useState<ReminderSettings|null>(null),[message,setMessage]=useState(''),[busy,setBusy]=useState(false);
 async function load(){const r=await fetch('/api/admin/trip-reminders',{cache:'no-store'});const d=await r.json();if(!r.ok)throw Error(d.error||'Please sign in to admin again.');setData(d);return d as Data;}
 useEffect(()=>{let active=true;fetch('/api/admin/trip-reminders',{cache:'no-store'}).then(async r=>{const d=await r.json();if(!r.ok)throw Error(d.error||'Please sign in to admin again.');if(active)setData(d);}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[]);
 async function action(body:object){setBusy(true);setMessage('');try{const r=await fetch('/api/admin/trip-reminders',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)});const result=await r.json();if(!r.ok)throw Error(result.error);setMessage(result.message);await load();}catch(e){setMessage(e instanceof Error?e.message:'Unable to complete action.');}finally{setBusy(false);}}
 const manual=(data?.manualPreviews||[]).filter(p=>p.sourceId===setting?.id);
 const scheduled=(data?.jobs||[]).filter(j=>!setting||j.id.includes(setting.id));
 const saved=data?.sources.find(s=>s.id===setting?.id)?.setting;
 const unsaved=Boolean(setting&&saved&&(['details','checklist','tips'] as const).some(k=>setting[k]!==saved[k]));
 return <main className={styles.page}><header className={styles.header}><div><p className={styles.eyebrow}>BUCKETLIST / TRAVELLER CARE</p><h1>Stay connected, every step.</h1><p>Prepare travellers, coordinate with vendors and celebrate journeys completed.</p></div><a href="/admin/crm">Back to CRM ↗</a></header>
 <div className={styles.toolbar}><span>Automatic sending: {!data?'Settings not loaded':data.enabled?'Enabled — scheduler required':'Off'}</span><button disabled={busy||!data} onClick={()=>void action({action:'test'})}>Send branded test to info@bucketlistadventure.in</button></div>
 {message&&<p role="status" className={styles.notice}>{message}</p>}{data?.warnings.map(w=><p className={styles.notice} key={w}>{w}</p>)}
 <div className={styles.grid}><section className={styles.panel}><h2>Trip reminders</h2><p>Emails at 7, 3 and 1 day before departure. Review requests the day after the trip, for bookings marked Completed.</p><label>Choose a trip<select value={setting?.id||''} onChange={e=>setSetting(data?.sources.find(s=>s.id===e.target.value)?.setting||null)}><option value="">Select a departure or custom booking</option>{data?.sources.map(s=><option key={s.id} value={s.id}>{s.start} · {s.title} · {s.id.startsWith('CUSTOM')?'Custom':'Departure'}</option>)}</select></label>
 {setting&&<><label>Meeting point, time and coordinator contact<textarea value={setting.details} maxLength={6000} onChange={e=>setSetting({...setting,details:e.target.value})}/></label><label>Things to carry<textarea value={setting.checklist} maxLength={6000} onChange={e=>setSetting({...setting,checklist:e.target.value})}/></label><label>Travel tips<textarea value={setting.tips} maxLength={6000} onChange={e=>setSetting({...setting,tips:e.target.value})}/></label>{(['customer_enabled','vendor_enabled','review_enabled'] as const).map((key,i)=><label className={styles.check} key={key}><input type="checkbox" checked={setting[key]} onChange={e=>setSetting({...setting,[key]:e.target.checked})}/>{['Customer preparation emails','Vendor coordination emails','Post-trip thank-you and review email'][i]}</label>)}<button disabled={busy} onClick={()=>void action({action:'save',...setting})}>Save reminder settings</button></>}
 </section><section className={styles.panel}><h2>Manual WhatsApp messages</h2><p>Confirmed bookings, including advance-paid bookings, can be contacted now. Email switches and the 30-day schedule do not control these previews. You review and send each message in WhatsApp.</p>
 {!setting&&<p>Select a trip to see its customer messages.</p>}
 {unsaved&&<p role="status">Save your changes to refresh the message before sending.</p>}
 {setting&&data&&data.manualPreviews===undefined&&<p>The preview update is not loaded on the server. Install both files and restart or redeploy the website.</p>}
 {setting&&data?.manualPreviews&&!manual.length&&<p>{data.manualReasons?.[setting.id]||'No eligible confirmed customer bookings for this trip.'}</p>}
 {manual.map(p=><details key={p.id} open><summary>{p.customer} · {p.reference}</summary><p>{p.phone||'Phone number missing'}</p>{p.reason&&<p role="status">{p.reason}</p>}<pre>{p.message}</pre>{p.whatsapp&&!unsaved&&<a className={styles.link} href={p.whatsapp} target="_blank" rel="noreferrer">Open WhatsApp message ↗</a>}</details>)}
 <h2>Scheduled email previews</h2><p>Eligible email messages in the next 30 days. Customer emails retain their 7/3/1-day schedule.</p>{scheduled.map(j=><details key={j.id}><summary>{j.date} · {j.kind.replaceAll('_',' ')}<br/>{j.trip}</summary><p>{j.recipient||'No email address'}</p><pre>{j.message}</pre>{j.whatsapp&&!unsaved&&!j.kind.startsWith('CUSTOMER_')&&<a className={styles.link} href={j.whatsapp} target="_blank" rel="noreferrer">Open WhatsApp message ↗</a>}</details>)}{data&&!scheduled.length&&<p>No scheduled emails within the next 30 days for this selection. Check the email switches and booking status. Manual WhatsApp previews are shown separately above.</p>}</section></div>
 <section className={styles.panel}><h2>Recent email activity</h2><p>Sent means accepted by the mail server. Uncertain or long-running Processing messages need checking before any manual resend.</p><div className={styles.table}><table><thead><tr><th>Time</th><th>Recipient</th><th>Subject</th><th>Status</th></tr></thead><tbody>{data?.history.map(h=><tr key={h.id}><td>{new Date(h.created_at).toLocaleString('en-IN',{timeZone:'Asia/Kolkata'})}</td><td>{h.recipient}</td><td>{h.subject}</td><td>{h.status}</td></tr>)}</tbody></table></div></section></main>;
}
